#the project name
site_name: lfp documents
#the project access address
dev_addr: 192.168.0.107:10086

# Repository
repo_name: lfp_tech_advance
repo_url: https://lee91.github.io/lfp_tech_advance/
edit_uri: ""
site_author: wytaitaislee

site_description: >-
  技术演进

# Copyright
copyright: Copyright &copy; 2019 - 2021 wytaitaislee

#pages layout
nav:
- 主页: index.md
- 介绍: introduction/introduction.md
- project component:
    - util: 
        - util: util/util.md
        - uitl cmd: util/util_cmd.md
        - uitl timer: util/util_timer.md
    - arch: arch/arch.md
    - arch adapter: arch_adapter/arch_adapter.md
    - exec: exec/exec.md
    - include: include/include.md
    - link order: lfp_linking/lfp_linking.md
    - main: main/main.md
    - menuconfig: menuconfig/menuconfig.md
    - lfp_rules.make: lfp_rules.make/lfp_rules.make.md
    - programming rules: programming_rules/programming_rules.md
    - modules:
        - about: modules/module.md
        - single_list: modules/single_list/single_list.md
        - double list: modules/double_list/double_list.md
        - socket app: modules/socket_app/socket_app.md
    - tools: tools/stats_tools.md
- extensions:
    - common knowledge: extensions/extensions.md
    - whiptail: extensions/whiptail.md
    - markdown syntax: extensions/markdown.md
- roads: roads/roads.md
#theme: readthedocs

# markdown extension
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - toc.integrate
  custom_dir: material
# 404 page
  static_templates:
    - 404.html
    
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  # 让浏览器的收藏夹中除显示相应的标题外，还以图标的方式区别不同的网站
  favicon: assets/github.svg
  # 网站页面中的图标(网站名前面的图标)
  icon:
    logo: github
    
# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

extra:
  alternate:
    - name: English
      link: https://squidfunk.github.io/mkdocs-material-insiders/en/
      lang: en
    - name: Deutsch
      link: https://squidfunk.github.io/mkdocs-material-insiders/de/
      lang: de
    - name: 日本語
      link: https://squidfunk.github.io/mkdocs-material-insiders/jp/
      lang: jp
