#the project name
site_name: LFP Docs
#the project access address
dev_addr: 127.0.0.1:8000
#pages layout
nav:
- Introduce: index.md
- Component:
    - roads: roads/roads.md
    - util: util/util.md
    - arch: arch/arch.md
    - arch_adapter: arch_adapter/arch_adapter.md
    - exec: exec/exec.md
    - include: include/include.md
    - link_order: link_order/link_order.md
    - main: main/main.md
    - menuconfig: menuconfig/menuconfig.md
    - modules:  modules/modules.md
    - rules.make: rules.make/rules.make.md
#theme: readthedocs
